name: Deploy blog-system-web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Preflight secrets
        run: |
          set -euo pipefail
          : "${SSH_HOST:?Missing secret SSH_HOST}"
          : "${SSH_USERNAME:?Missing secret SSH_USERNAME}"
          : "${SSH_PRIVATE_KEY:?Missing secret SSH_PRIVATE_KEY}"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

  deploy-web:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20 (build artifacts on runner)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (runner)
        run: |
          npm ci --no-audit --fund=false

      - name: Build Next.js (runner)
        run: |
          npm run build

      - name: Prune dev deps (runner)
        run: |
          npm prune --omit=dev

      - name: Prepare remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            exec 2>&1
            sudo mkdir -p /opt/blog-system-web
            # chown to the SSH user to ensure write permission during scp
            sudo chown -R "${USER:-$LOGNAME}":"${USER:-$LOGNAME}" /opt/blog-system-web

      - name: Upload project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            package.json,package-lock.json,next.config.mjs,next-env.d.ts,middleware.ts,.next,node_modules,deploy
          target: /opt/blog-system-web
          overwrite: true


      - name: Deploy and restart service
        uses: appleboy/ssh-action@v1.0.3
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          APP_PORT: ${{ secrets.APP_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NEXT_PUBLIC_API_BASE_URL,APP_PORT,GITHUB_SHA
          script: |
            set -euo pipefail
            exec 2>&1
            cd /opt/blog-system-web
            chmod +x deploy/linux/deploy_web.sh
            NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-}" APP_PORT="${APP_PORT:-3000}" GIT_SHA="${GITHUB_SHA:-manual}" ./deploy/linux/deploy_web.sh

      - name: Verify service health (intra-host)
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: APP_PORT
          script: |
            set -euo pipefail
            exec 2>&1
            sleep 5
            curl -fsS "http://127.0.0.1:${APP_PORT}/api/health" | sed -n '1,200p'

      # No domain verification step for direct mode


